# Generated by Django 4.2.7 on 2024-01-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('brand', 'brand'), ('type', 'type')], max_length=100),
        ),
    ]
