# Generated by Django 4.2.7 on 2024-01-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('make', 'make'), ('model', 'model'), ('enginecc', 'enginecc'), ('year', 'year')], max_length=100),
        ),
    ]
