# Generated by Django 4.2.7 on 2024-01-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
