# Generated by Django 4.2.7 on 2024-02-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_productrequest_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='total',
        ),
    ]
