# Generated by Django 4.2.7 on 2024-03-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_address_account_city_account_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_vendor',
        ),
    ]
