# Generated by Django 4.2.7 on 2024-01-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffRole',
        ),
    ]
