# Generated by Django 4.2.7 on 2024-03-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_is_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'client profile', 'verbose_name_plural': 'client profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../static/images/avatars/user.png', null=True, upload_to='userprofile/'),
        ),
    ]
