# Generated by Django 4.2.7 on 2024-01-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffposition_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='positions',
        ),
        migrations.AddField(
            model_name='staff',
            name='positions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffposition'),
            preserve_default=False,
        ),
    ]
