# Generated by Django 4.2.7 on 2024-01-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_staff_positions_staff_positions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='positions',
            new_name='position',
        ),
    ]
