# Generated by Django 4.2.7 on 2024-01-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0007_account_groups_account_user_permissions_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='groups',
        ),
        migrations.AddField(
            model_name='staff',
            name='groups',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
