# Generated by Django 4.2.7 on 2024-01-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_positions_staff_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
